///////////////////////////////////////////////////////////
//  IModeloLectura.cs
//  Implementation of the Interface IModeloLectura
//  Generated by Enterprise Architect
//  Created on:      10-Jun.-2016 4:46:31 p. m.
//  Original author: JUAN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using Binapsis.Plataforma.Estructura;

namespace Binapsis.Plataforma.Serializacion.Lectura
{
	internal interface IModeloLectura
    {
        IObjetoDatos Instanciar(int refid, string uri, string tipo);
        void Agregar(IMetodoAsociacion asociacion);
        void Resolver(int refid, int propietario, int propiedad);

        IMetodoLectura Crear(Metodo metodo);        
        IMetodoLectura Crear(int refid, int longitud);
        IMetodoLectura Crear(int refid, int longitud, IObjetoDatos od);
        IMetodoLectura Crear(int refid, int longitud, int propietario, int propiedad);
        
	}
}